
    create table Residences (
        id bigint generated by default as identity (start with 1),
        address varchar(255),
        cal timestamp,
        dayOfMonth integer not null,
        primary key (id)
    )
