
    create table Actuator (
        residence_id bigint generated by default as identity (start with 1),
        device_id bigint,
        primary key (residence_id)
    )

    create table Administrator (
        administrator_id bigint generated by default as identity (start with 1),
        password varchar(255),
        username varchar(255),
        fullname varchar(255),
        registrationDate timestamp,
        residenceAddress varchar(255),
        primary key (administrator_id)
    )

    create table Area (
        area_id bigint generated by default as identity (start with 1),
        area_name varchar(255),
        coordinate varbinary(255),
        radius float,
        primary key (area_id)
    )

    create table Category (
        category_id bigint generated by default as identity (start with 1),
        fixedCharge numeric(19,2),
        maxConsumption float,
        minConsumption float,
        name varchar(255),
        variableCharge numeric(19,2),
        primary key (category_id)
    )

    create table Client (
        client_id bigint generated by default as identity (start with 1),
        password varchar(255),
        username varchar(255),
        fullname varchar(255),
        registrationDate timestamp,
        residenceAddress varchar(255),
        number_id varchar(255),
        type_id varchar(255),
        phone_number varchar(255),
        score integer,
        category_id bigint,
        primary key (client_id)
    )

    create table Device (
        device_type varchar(31) not null,
        device_id bigint generated by default as identity (start with 1),
        hourlyConsumption numeric(19,2),
        name varchar(255),
        dailyUseEstimation numeric(19,2),
        primary key (device_id)
    )

    create table DeviceInfo (
        deviceInfo_id bigint generated by default as identity (start with 1),
        bajoConsumo boolean,
        consumption double,
        desc varchar(255),
        inteligente boolean,
        maxHsUse integer,
        minHsUse integer,
        name varchar(255),
        primary key (deviceInfo_id)
    )

    create table Measure (
        measure_id bigint generated by default as identity (start with 1),
        magnitude varchar(255),
        value numeric(19,2),
        sensor_id bigint,
        primary key (measure_id)
    )

    create table Residence (
        residence_id bigint generated by default as identity (start with 1),
        address varchar(255),
        area_id bigint,
        client_id bigint,
        primary key (residence_id)
    )

    create table Rule (
        rule_id bigint generated by default as identity (start with 1),
        actuator_id bigint,
        sensor_id bigint,
        primary key (rule_id)
    )

    create table Sensor (
        sensor_id bigint generated by default as identity (start with 1),
        intervalInSeconds float,
        device_id bigint,
        primary key (sensor_id)
    )

    create table StateHistory (
        stateHistory_id bigint generated by default as identity (start with 1),
        end timestamp,
        start timestamp,
        state varchar(255),
        device_id bigint,
        primary key (stateHistory_id)
    )

    create table TimeIntervalDevice (
        timeIntervalDevice_id bigint generated by default as identity (start with 1),
        consuming boolean,
        end timestamp,
        start timestamp,
        device_id bigint,
        primary key (timeIntervalDevice_id)
    )

    create table Transformer (
        transformer_id bigint generated by default as identity (start with 1),
        coordinate varbinary(255),
        area_id bigint,
        primary key (transformer_id)
    )

    alter table Actuator 
        add constraint FK_kohhg7urkrakort98twokbuqd 
        foreign key (device_id) 
        references Device

    alter table Client 
        add constraint FK_cowu1nimxw9ilbpvwxwjof1qg 
        foreign key (category_id) 
        references Category

    alter table Measure 
        add constraint FK_s6r4ccrgjqb1i1gwrc56m33f 
        foreign key (sensor_id) 
        references Sensor

    alter table Residence 
        add constraint FK_g9f5caryapdu14l0l89wrx56f 
        foreign key (area_id) 
        references Area

    alter table Residence 
        add constraint FK_g47mob20x3tths1xqyuy7h0ou 
        foreign key (client_id) 
        references Client

    alter table Rule 
        add constraint FK_dq9oegjg8mw8pqrxbd2v2pj51 
        foreign key (actuator_id) 
        references Actuator

    alter table Rule 
        add constraint FK_bfot57sbj6wxbqp977t11etrt 
        foreign key (sensor_id) 
        references Sensor

    alter table Sensor 
        add constraint FK_ppmi5j5lawo8147qlw48a2pmd 
        foreign key (device_id) 
        references Device

    alter table StateHistory 
        add constraint FK_jqo0nvgssmhbj4b6604l3yb1a 
        foreign key (device_id) 
        references Device

    alter table StateHistory 
        add constraint FK_jqo0nvgssmhbj4b6604l3yb1a 
        foreign key (device_id) 
        references Device

    alter table TimeIntervalDevice 
        add constraint FK_lbfr0evtfbgib80598p843dh9 
        foreign key (device_id) 
        references Device

    alter table TimeIntervalDevice 
        add constraint FK_lbfr0evtfbgib80598p843dh9 
        foreign key (device_id) 
        references Device

    alter table TimeIntervalDevice 
        add constraint FK_lbfr0evtfbgib80598p843dh9 
        foreign key (device_id) 
        references Device

    alter table Transformer 
        add constraint FK_2o1pg2dtnof1g1q7spbt8s9rh 
        foreign key (area_id) 
        references Area
