
    create table Administrator (
        administrator_id bigint generated by default as identity (start with 1),
        password varchar(255),
        username varchar(255),
        fullname varchar(255),
        registrationDate timestamp,
        residenceAddress varchar(255),
        primary key (administrator_id)
    )

    create table Category (
        category_id bigint generated by default as identity (start with 1),
        fixedCharge numeric(19,2),
        maxConsumption float,
        minConsumption float,
        name varchar(255),
        variableCharge numeric(19,2),
        primary key (category_id)
    )

    create table Client (
        client_id bigint generated by default as identity (start with 1),
        password varchar(255),
        username varchar(255),
        fullname varchar(255),
        registrationDate timestamp,
        residenceAddress varchar(255),
        number_id varchar(255),
        type_id varchar(255),
        phone_number varchar(255),
        score integer,
        category_id bigint,
        primary key (client_id)
    )

    create table Residence (
        residence_id bigint generated by default as identity (start with 1),
        address varchar(255),
        client_id bigint,
        primary key (residence_id)
    )

    alter table Client 
        add constraint FK_cowu1nimxw9ilbpvwxwjof1qg 
        foreign key (category_id) 
        references Category

    alter table Residence 
        add constraint FK_g47mob20x3tths1xqyuy7h0ou 
        foreign key (client_id) 
        references Client
